import os
dest = r"C:\Users\Dell\Desktop\eniveroment\frontend\src\components\LiveStreamRoom.jsx"
# Read existing and strip the last 3 bad lines
with open(dest, encoding="utf-8") as f:
    lines = f.read().splitlines()
# Remove lines starting from "const dq"
while lines and "const dq" in lines[-1]:
    lines.pop()
while lines and "const RED_" in lines[-1]:
    lines.pop()
# Add return JSX
jsx = [
  "  return (",
  "    <div className=\"min-h-screen bg-slate-900 flex flex-col\">",
  "      <header className=\"h-16 flex items-center justify-between px-6 border-b border-slate-800\">",
  "        <div className=\"flex items-center gap-3\">",
  "          {!isStreamer && (",
  "            <Link to=\"/live\" className=\"p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors\">",
  "              <ArrowLeft className=\"w-4 h-4\" />",
  "            </Link>",
  "          )}",
  "          <div className=\"flex items-center gap-2.5\">",
  "            <div className=\"w-7 h-7 bg-indigo-600 rounded-lg flex items-center justify-center\">",
  "              <Shield className=\"w-3.5 h-3.5 text-white\" />",
  "            </div>",
  "            <span className=\"text-sm font-bold text-white\">",
  "              CrimeReport{\" \"}",
  "              <span className={isStreamer ? \"text-red-500\" : \"text-indigo-400\"}>",
  "                {isStreamer ? \"LIVE\" : \"Viewer\"}",
  "              </span>",
  "            </span>",
  "          </div>",
  "        </div>",
  "        <div className=\"flex items-center gap-3\">",
  "          {(started || connected) && (",
  "            <span className={`flex items-center gap-1.5 text-xs font-semibold ${isStreamer ? \"text-red-400\" : \"text-emerald-400\"}`}>",
  "              <span className={`w-2 h-2 rounded-full ${isStreamer ? \"bg-red-500 animate-pulse\" : \"bg-emerald-500\"}`} />",
  "              {isStreamer ? \"LIVE\" : \"CONNECTED\"}",
  "            </span>",
  "          )}",
  "          {isStreamer && started && (",
  "            <span className=\"flex items-center gap-1.5 text-xs text-slate-400\">",
  "              <Users className=\"w-3.5 h-3.5\" />",
  "              {viewerCount} viewers",
  "            </span>",
  "          )}",
  "        </div>",
  "      </header>",
  "      <main className=\"flex-1 flex items-center justify-center p-6\">",
  "        <div className=\"w-full max-w-3xl space-y-4\">",
  "          <div className=\"aspect-video bg-black rounded-2xl overflow-hidden border border-slate-700 relative\">",
  "            {isStreamer ? (",
  "              <>",
  "                <video ref={localVideoRef} autoPlay muted playsInline className=\"w-full h-full object-cover\" />",
  "                {!started && (",
  "                  <div className=\"absolute inset-0 flex flex-col items-center justify-center gap-4\">",
  "                    <Video className=\"w-12 h-12 text-slate-600\" />",
  "                    <p className=\"text-slate-400 text-sm\">Camera preview will appear here</p>",
  "                  </div>",
  "                )}",
  "              </>",
  "            ) : (",
  "              <>",
  "                <video ref={remoteVideoRef} autoPlay playsInline className=\"w-full h-full object-cover\" />",
  "                {!connected && (",
  "                  <div className=\"absolute inset-0 flex flex-col items-center justify-center gap-3\">",
  "                    <div className=\"w-8 h-8 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin\" />",
  "                    <p className=\"text-slate-400 text-sm\">Connecting to stream...</p>",
  "                    <p className=\"text-slate-600 text-xs\">Room: {streamId}</p>",
  "                  </div>",
  "                )}",
  "              </>",
  "            )}",
  "          </div>",
  "          <div className=\"flex items-center justify-center gap-3\">",
  "            {isStreamer && !started && (",
  "              <button onClick={handleStart} disabled={starting}",
  "                className=\"flex items-center gap-2 px-8 py-3 bg-red-600 hover:bg-red-700 disabled:opacity-50 text-white font-semibold rounded-xl transition-colors\">",
  "                {starting",
  "                  ? <><div className=\"w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin\" />Starting...</>",
  "                  : <><Video className=\"w-4 h-4\" />Go Live</>}",
  "              </button>",
  "            )}",
  "            {isStreamer && started && (",
  "              <>",
  "                <button onClick={toggleMute}",
  "                  className={`p-3 rounded-xl transition-colors ${muted ? \"bg-red-600 text-white\" : \"bg-slate-700 text-slate-300 hover:bg-slate-600\"}`}>",
  "                  {muted ? <MicOff className=\"w-5 h-5\" /> : <Mic className=\"w-5 h-5\" />}",
  "                </button>",
  "                <button onClick={toggleVideo}",
  "                  className={`p-3 rounded-xl transition-colors ${videoOff ? \"bg-red-600 text-white\" : \"bg-slate-700 text-slate-300 hover:bg-slate-600\"}`}>",
  "                  {videoOff ? <VideoOff className=\"w-5 h-5\" /> : <Video className=\"w-5 h-5\" />}",
  "                </button>",
  "                <button onClick={handleStop}",
  "                  className=\"flex items-center gap-2 px-6 py-3 bg-red-700 hover:bg-red-800 text-white font-semibold rounded-xl transition-colors\">",
  "                  <PhoneOff className=\"w-4 h-4\" />End Stream",
  "                </button>",
  "              </>",
  "            )}",
  "          </div>",
  "        </div>",
  "      </main>",
  "    </div>",
  "  )",
  "}"
]
lines.extend(jsx)
with open(dest, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("Done. Lines:", len(lines), "Size:", os.path.getsize(dest))
